spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
      acks: 1
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: aws
      properties:
        spring.json.trusted.packages: "*"
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/kafka
    username: admin
    password: 12345
  flyway:
    url: jdbc:postgresql://localhost:5432/kafka
      username: admin
      password: 12345
      locations: classpath:db/migration

server:
  port: 8066

kafka-topics:
  notification: notification
  recipient: recipient